[project]
name = "ea-ai"
version = "0.1.0"
description = "Minimal structural language model lab"
readme = "README.md"
authors = [
    { name = "guoshijun", email = "guoshijun@regen-bio.com" }
]
requires-python = ">=3.9"

[project.scripts]
ea-ai = "ea_ai:main"
struct = "struct_llm.cli:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
